### ISSUE TITLE
3.0.0-beta vs 3.0.3

### ISSUE THREAD

**Issue by pavelloz** [onokumus/metismenu#175]
I dont understand the naming.

3.0.0-beta is in typescript and doesnt require jquery - when couple days ago 3.0.3 has been released i assumed it is a continuation of 3.x branch and upgrade will be seamless (according to semver it should), but it as it turns out 3.0.x is a totally different beast, not in typescript and it is requiring jquery in the first line.

So, how should i understand 3.0.0-beta vs 3.0.x? I dont want to include jquery in my project so ill stick to 3.0.0-beta - will it be promoted to the mainstream?

**Comment by onokumus** [comment]
Hi @pavelloz 

This is my fault.

- I wanted to finish jQuery dependency with [metismenu (with jQuery)](https://github.com/onokumus/metismenu)'s 3.0.0 version. But then I decided to turn it into a different package ([metismenujs (without jQuery)](https://github.com/onokumus/metismenujs)). Because there were too many users and they were might not be able to adapt to this change. After this decision, I published [metismenujs (without jQuery)](https://github.com/onokumus/metismenujs) package which do not require jQuery.

- There was a conflict between the css classes of [metismenu (with jQuery)](https://github.com/onokumus/metismenu) and the css classes of some frameworks. I've changed css classes in the v3 to eliminate this. In the v3.0.3 there are css classes that are incompatible with the v2.

It is the [metismenujs (without jQuery)](https://github.com/onokumus/metismenujs) package that you don't want jquery dependency. You should be use [metismenujs (without jQuery)](https://github.com/onokumus/metismenujs)

**Comment by pavelloz** [comment]
Ouh, i didnt see the metismenujs repo before, thanks for the heads up :)
