### ISSUE TITLE
Suggestion to make the .arrow class name more specific

### ISSUE THREAD

**Issue by rderharo** [onokumus/metisMenu#34]
I'm trying to implement the intl-tel-input plugin and there is a conflict with metisMenu regarding the `.arrow` class.

The issue is that while intl-tel-input specifies the selector as specific:
`.intl-tel-input .selected-flag .arrow {`

metisMenu has a broad selector that captures everything, including other elements:
`.arrow {`

This results in some important styles being overwritten and forces me to reset the defaults on my app's CSS.

Is it possible to refactor the stylesheet for metisMenu to be more specific as to isolate the effect it has on other controls in the same application?

**Comment by lenamtl** [comment]
+1

**Comment by onokumus** [comment]
https://github.com/onokumus/metisMenu/blob/master/dist/metisMenu.css#L10

**Comment by rderharo** [comment]
Thank you!

**Comment by mpkhoury** [comment]
I am using metismenu in a rails web site and an akward behavior is happening. Maybe you have already came across with it. I will try to reproduce the issue:
a) menu (=a partial in rails) is collapsed on the initial state
b) click item that expands their children
c) click children item that fires a link to show a specific page
d) menu collapses (I needed it to stay opened and the option selected highlighted): it seems a JS event is trigered, but I don't know how to intercept in order to prevent it
Any thoughts on how to solve it is welcome :D
